// quotes.js — FinkHub rotating quotes
// Add new quotes here. One string per line. Order is randomized on load.

export const QUOTES = [
  "Options Spreads: It's basically sports betting for people who own too many Patagonia vests and like to pretend their parlays are \"mathematical models.\"",
  "The \"Hedge\": Using a spread is just losing money with a seatbelt on\u2014it's like betting on Red at the casino while also betting on \"Not-Quite-As-Red\" so you can call it risk management.",
  "Iron Condors: This strategy involves picking two numbers the stock won't hit; it's the financial version of charging the market rent for staying in its room\u2014right up until the market decides to move out in the middle of the night.",
  "Covered Calls: The \"I'm the House\" strategy, until the stock moons and you realize you're the only person who sold their house at 2019 prices while your neighbors are all retiring on Mars.",
  "0DTE (Zero Days to Expiration): Buying these is just paying a premium to watch a countdown timer tell you your net worth is now officially a tax write-off.",
  "Buying Puts: It's like buying fire insurance on your neighbor's house, except you're secretly standing in their driveway with a match praying for a \"market correction.\"",
  "The Greeks: Delta, Gamma, and Theta aren't math; they're just the names of the monsters under an options trader's bed that eat their account balance while they sleep.",
  "Theta Decay: The slow, agonizing process of watching your portfolio evaporate purely because the Earth continues to rotate around the Sun.",
  "Implied Volatility (IV) Crush: This is the market's way of saying, \"I know you were right about the earnings report, but I'm still going to take your lunch money because you were too excited about it.\"",
  "Margin Calls: The ultimate \"Game Over\" screen that proves your \"sophisticated strategy\" was actually just three casinos stacked on top of each other in a trench coat.",
  "The Ice Cube: Buying an option is like buying a literal ice cube in the desert. You might have a great plan for it, but Theta is the sun that doesn't care about your \"thesis.\"",
  "The Weekend Tax: Theta is the only thief that works Saturdays. You go to sleep Friday feeling like a genius and wake up Monday to find your portfolio evaporated 15% just because the Earth kept spinning.",
  "The \"Hope\" Drain: Theta is the realization that even if the stock finally goes your way, you spent more on time decay than the profit is worth. It's like winning a race but spending the prize money on gas to get to the track.",
  "The Seller's Employee: If you're selling options, Theta is your loyal worker who never takes a day off. If you're buying them, Theta is the high-interest credit card you forgot to pay.",
  "The Wash Sale Rule: The IRS's way of reminding you that you can't just delete your mistakes and start over like it's a video game.",
  "The PDT Rule: A velvet rope designed to keep you out of the \"VIP section of losing money\" until you have at least $25,000 to set on fire.",
  "LEAPS: Buying these is like watching a slow-motion car crash that takes two years to actually hit the wall.",
  "Early Assignment: The financial equivalent of a \"surprise party\" where the only guest is a massive debt you didn't see coming.",
  "Bid-Ask Spreads: The hidden tax on your optimism. You're down 5% the second you click \"buy\" just for the privilege of participating in your own demise.",
  "Technical Analysis: Drawing lines on a chart until they look like a staircase to heaven, right before the market pushes you down the elevator shaft.",
  "RSI & MACD: Financial astrology for people who think a \"Golden Cross\" is a sign from God instead of a lagging indicator of their own hubris.",
  "Paper Trading: The only time you'll ever be a millionaire. It's like being the world's best driver while sitting in a parked car.",
  "Risk Management: The thing you promise to start doing tomorrow, right after this one last \"guaranteed\" play recovers the losses from the previous three \"guaranteed\" plays.",
  "Max Pain: The theory that the market will gravitate toward the price that makes the most people miserable. It's not a conspiracy; it's just the market's personality.",
  "Jerome Powell: The only man on Earth who can turn your life savings into a cautionary tale just by clearing his throat during a press conference.",
  "Market Makers: The silent ghosts who ensure that the \"bid\" is always exactly one cent lower than you need it to be to feel any joy.",
  "Trading on Margin: Using the bank's money to prove you're smarter than the bank. Spoiler: The bank has a much bigger building than you do.",
  "Deep OTM Calls: \"Low-probability, high-convexity events\" is just a fancy way of saying you're buying lottery tickets from a guy in a suit.",
  "FOMO: The irresistible urge to buy at the absolute top because you saw a guy on the internet with a cartoon avatar claim he's \"never been more bullish.\"",
  "Revenge Trading: Trying to \"win back\" money from the market is like trying to fistfight a hurricane because it blew your hat off.",
  "The Long Straddle: A strategy where you bet the stock will move, only for it to stay perfectly still out of sheer spite for your \"delta-neutral\" genius.",
  "Account Liquidation: On the bright side, you don't actually need two kidneys to trade, but you definitely need two to pay for the therapy session after this trade.",
];
